version: '3.7'
services:
  backend:
    build:
        context: ./docker/backend
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/app
    environment:
        - PYTHONUNBUFFERED=1
        - ENVIRONMENT=prod
        - GOOGLE_API_KEY_ID=${GOOGLE_API_KEY_ID}

  frontend:
      build:
          context: ./docker/frontend
      restart: always
      working_dir: /usr/src/app
      ports:
          - '3000:3000'
      volumes:
          - ./frontend:/usr/src/app
volumes:
    backend-data:
